### ISSUE TITLE
How to access reference file from Cloud Storage

### ISSUE THREAD

**Issue by romagnolid** [gatk-workflows/gatk4-data-processing#10]
Should I download reference files locally or is it possible to access them remotely? In that case, how can I do that?

**Comment by bshifaw** [comment]
If you plan to run the workflow locally then you'll need to download the files. If you plan the run the workflow on the google cloud platform then you wont need to download the files. It might be possible to use gatk4 NIO but that would require some edits to the workflow, if your intersted in NIO please ask your question in the [wdl/cromwell forum](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team). And in general please direct questions to the Gatk forums (GATK, Firecloud, WDL+Cromwell)

Link to [(How to) Execute Workflows from the gatk-workflows Git Organization](https://software.broadinstitute.org/gatk/documentation/article?id=12521) tutorial 

Hope this helps

**Comment by romagnolid** [comment]
Thank you, I'll post further questions there.
