### ISSUE TITLE
question about bwa mem and how to use this for whole NA12878

### ISSUE THREAD

**Issue by Pharah01** [gatk-workflows/gatk4-data-processing#11]
Dear GATK4 team, 
Firstly, thanks very much for amazing pipelines.
I am using this wdl and hg38 json file to run my own data (NA12878, dowload fastq, using FastqToSam to generate my own ubam file list) on my Virtual Machine. 

Question1:
	${bwa_path}${bwa mem -K 100000000 -p -v 3 -t 16 -Y $bash_ref_fasta} /dev/stdin -  2> >(tee ${output_bam_basename}.bwa.stderr.log >&2) \
    | \
		samtools view -1 - > ${output_bam_basename}.bam
Can you explain a little bit about this two lines, what it did. I cannot find -Y argument in bwa mem usage page.

Question2:
I tried to benchmarking this gatk4 best practice workflow with NA12878, 12891, 12892 in my VM. Could keep all parameters as you used in the board offered wdl and json script just change the input files to my own?

I ran this whole process in my VM. After two days, with 16 threads, it showed: workflow successfully completed.
I found a little bit funny result: my input 4 ubams, each of them sized 33G, my aligned.duplicates-marked.sorted.bam sized around 120G. After, BQSR, the final output bam file sized around 70 G.

I used exactly the same wdl file I offered above, in json file, just changed input as my own 4 bam files passing as a ubam list, and keep using the ref and known sites resource file offered in above json file. And certainly, I adjust all files path to its absolute path in my virtual machine.

Do you think this is normal or I did something wrong? I use NA12878.

**Comment by bshifaw** [comment]
- The following material is provided by the GATK Team. Please post any questions or concerns to one of our forum sites : [GATK](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team/) , [FireCloud](https://gatkforums.broadinstitute.org/firecloud/categories/ask-the-firecloud-team) or [Terra](https://broadinstitute.zendesk.com/hc/en-us/community/topics/360000500432-General-Discussion) , [WDL/Cromwell](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team).

- Here is an explanation of a similar workflow that you might find useful: [Reference implementation: PairedEndSingleSampleWf pipeline](https://software.broadinstitute.org/gatk/documentation/article?id=7899)
