### ISSUE TITLE
Additional requirement: bwa index files must be in same source directory

### ISSUE THREAD

**Issue by kclem** [gatk-workflows/gatk4-data-processing#12]
You should list as an additional requirement that bwa index files must be in the same source directory.

When cromwell runs, it creates a separate directory in the 'inputs' folder for input files to each command coming from separate folders. So if the genome.fa is originally in a different folder than the genome.fa.fai, cromwell will link them into different folders in the task inputs folder, causing bwa to fail because the index files are not present with the sequence files. Unfortunately, the SamToFastqAndBwaMem task will fail with a very unhelpful error: ```Error in writing fastq file /dev/stdout```.

Perhaps the pipeline should be modified to copy all bwa sequence and index files to a common folder before execution to avoid this error?

**Comment by bshifaw** [comment]
Please post any questions or concerns to one of our forum sites where we have staff to answer questions in a timely manner : [GATK](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team/) , [FireCloud](https://gatkforums.broadinstitute.org/firecloud/categories/ask-the-firecloud-team) , [WDL/Cromwell](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team).

Cromwell will automatically copy over any files declared in the task block to cromwells working directory where the task command will have access.

**Comment by bshifaw** [comment]
Added to https://github.com/gatk-workflows/gatk4-data-processing/pull/14#issue-254059569
