### ISSUE TITLE
Running pipeline locally

### ISSUE THREAD

**Issue by samkleeman1** [gatk-workflows/gatk4-data-processing#5]
Hi,

I am hoping to run this pipeline on our internal cluster - without any use of Docker or cloud computing. What modifications do I need to make to the script? Currently I am getting a long list of error messages when I try to run it (largely relating to problems connecting to Docker). 

Thanks,

Sam Kleeman

**Comment by bshifaw** [comment]
1. The runtime parameters and variables associated with it will need to be removed, or you can give those variables fictitious inputs in the json (Cromwell will ignore them).
2. The tool paths must match the location of your local tools.
