### ISSUE TITLE
How to make BWA visible/accessible from a GATK4 container ?

### ISSUE THREAD

**Issue by 3i-v** [gatk-workflows/gatk4-data-processing#6]
Dear, 
I have installed Docker (Docker version 18.03.0-ce, build 0520e24), on an internal server; I have also pull the GATK4 image (broadinstitute/gatk:4.0.3.0) and GOTC image (broadinstitute/genomes-in-the-cloud:2.3.1-1512499786).

I am running a modified WDL file (as a 1st test) from a GATK4 container, but I do not succeed to get the BWA version from there :

```
[2018-04-27 19:11:47,27] [info] WorkflowManagerActor WorkflowActor-673c1f7d-7124-47b6-81d6-f4ff110eed60 is in a termin al state: WorkflowSucceededState
[2018-04-27 19:11:52,64] [info] SingleWorkflowRunnerActor workflow finished with status '**Succeeded**'.
{
  "outputs": {
    "PreProcessingForVariantDiscovery_GATK4_vs.GetBwaVersion.version": ""
  },
  "id": "673c1f7d-7124-47b6-81d6-f4ff110eed60"
}

```
---
When shifting into a GOTC container, the command  ./bwa 2>&1 | grep -e '^Version' give me the BWA version indeed (Version: 0.7.15-r1140)

How can I make the GOTC image visible from GATK4 or another way to ask is: How BWA could be seen from GATK4 ?
I probably miss something obvious, but I did not found yet.

Context:
Because I am new to Docker and .WDL, I have first limited the WDL file to the 1st task that is "task GetBwaVersion".

.json file:
```
{
  "PreProcessingForVariantDiscovery_GATK4_vs.gotc_path": "/usr/gitc/",
  "PreProcessingForVariantDiscovery_GATK4_vs.gotc_docker": "broadinstitute/genomes-in-the-cloud:2.3.1-1512499786"
}
```

Command line:
**(gatk) root@(...):/gatk/my_data**# java -jar ./4-pipelining/jars/cromwell-30.2.jar  run  ./myfile.wdl

Here is the WDL I execute, (and again, I run it from a GATK4 container, as described in the command line)

```
# WORKFLOW DEFINITION 
workflow PreProcessingForVariantDiscovery_GATK4 {

  String gotc_path
  String gotc_docker

  call GetBwaVersion {
    input: 
      docker_image = gotc_docker,
      bwa_path = gotc_path
  }

}
# TASK DEFINITIONS

# Get version of BWA
task GetBwaVersion {

  String docker_image
  String bwa_path

  command {
    ${bwa_path}bwa 2>&1 | \
    grep -e '^Version' | \
    sed 's/Version: //'
  }
  output {
    String version = read_string(stdout())
  }
}
```

Thank you for your help,
Best Regards,
v.

**Comment by bshifaw** [comment]
Hi,

Please repost this question or a link to this git issue to the gatk forum where the dev team can view your question.
[https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team)

**Comment by 3i-v** [comment]
Thank you @bshifaw
